# Quickstart: Your First Bayesian VAR

This tutorial walks you through fitting a Bayesian VAR model to macroeconomic data using Litterman.

In [1]:
import numpy as np
import pandas as pd

from litterman import VAR, VARData, select_lag_order
from litterman.samplers import NUTSSampler

## Create some synthetic data

We'll simulate a simple VAR(1) process with two variables.

In [2]:
rng = np.random.default_rng(42)
T = 200
y = np.zeros((T, 2))
for t in range(1, T):
    y[t] = 0.5 * y[t - 1] + rng.standard_normal(2) * 0.1

index = pd.date_range("2000-01-01", periods=T, freq="QS")
data = VARData(endog=y, endog_names=["gdp", "inflation"], index=index)
data

VARData(endog=array([[ 0.00000000e+00,  0.00000000e+00],
       [ 3.04717080e-02, -1.03998411e-01],
       [ 9.02809736e-02,  4.20572663e-02],
       [-1.49963032e-01, -1.09189318e-01],
       [-6.21974757e-02, -8.62189180e-02],
       [-3.27788536e-02, -1.28413852e-01],
       [ 7.15503707e-02,  1.35722677e-02],
       [ 4.23782551e-02,  1.19510255e-01],
       [ 6.79400618e-02, -2.61741190e-02],
       [ 7.08451093e-02, -1.08975320e-01],
       [ 1.23267585e-01, -5.94802509e-02],
       [ 4.31475560e-02, -9.78330799e-02],
       [ 1.43827912e-01, -6.43694882e-02],
       [ 2.90811737e-02, -6.73980991e-02],
       [ 6.77715054e-02,  2.84535687e-03],
       [ 7.51590139e-02,  4.45047787e-02],
       [ 2.51744267e-01, -1.83891123e-02],
       [ 7.46478606e-02, -9.05718290e-02],
       [ 9.89218726e-02,  6.76113148e-02],
       [ 3.80661905e-02, -5.02099903e-02],
       [-6.34150263e-02,  3.99542836e-02],
       [ 4.26179040e-02,  7.42925686e-02],
       [-4.52420187e-02,  6.03624166e-02],
       [-1.09524285e-02,  5.20500680e-02],
       [ 8.16666636e-02,  4.83845889e-02],
       [ 1.08724688e-01,  3.09502014e-02],
       [ 8.32742839e-02,  7.86039233e-02],
       [-1.04078440e-01,  7.33484000e-03],
       [-9.90764854e-02, -6.02203648e-02],
       [-7.70524678e-02,  1.19383949e-01],
       [-1.25109345e-01,  1.56519810e-01],
       [-2.30841650e-01,  4.47714019e-02],
       [-9.91455184e-02,  8.10079341e-02],
       [ 2.15498988e-02,  1.19838691e-01],
       [-2.40975578e-02,  1.36841660e-02],
       [ 7.37488092e-02, -1.22883495e-02],
       [-9.06942277e-02, -1.19472896e-01],
       [-1.37292342e-01, -1.00203737e-02],
       [-5.44035976e-02,  6.40383486e-02],
       [-6.99270634e-02,  4.78731434e-02],
       [ 2.75955077e-02, -6.99808227e-03],
       [ 5.94752776e-02, -6.96916352e-02],
       [-6.56774586e-03, -7.30196070e-02],
       [-1.22867837e-01,  1.21874446e-02],
       [-1.08374153e-01,  7.34313416e-03],
       [-6.11241049e-03,  4.83246847e-02],
       [ 6.34823057e-02,  1.43137939e-02],
       [-1.05886784e-02, -8.14924146e-04],
       [-1.74027783e-01, -1.45118709e-01],
       [-2.19283853e-01, -1.72284037e-01],
       [-6.96645036e-02, -1.76689924e-01],
       [-7.26485072e-02,  4.15778677e-02],
       [-7.19506507e-02,  9.45404907e-02],
       [-1.29337093e-01,  2.67264896e-02],
       [-1.59670752e-01, -2.05400628e-02],
       [ 4.19543766e-03, -1.83002074e-01],
       [ 4.55400832e-02, -6.77274766e-02],
       [-3.66449540e-02, -1.78469524e-01],
       [-1.11095262e-02, -1.42184033e-01],
       [ 1.77128580e-02, -6.89068018e-02],
       [ 1.69034318e-01, -5.83889637e-02],
       [-1.78325902e-02, -1.12669183e-02],
       [ 1.30833733e-02,  1.30285298e-01],
       [ 9.00528112e-02,  1.00829755e-01],
       [ 1.91356695e-01, -6.84614279e-02],
       [ 3.17031941e-02, -1.26888308e-01],
       [-2.31293833e-02, -2.01112769e-01],
       [ 5.19504030e-02, -1.22778654e-01],
       [-1.21105428e-01, -1.62947235e-01],
       [-2.92013292e-02,  2.33903920e-03],
       [ 1.85072425e-01,  2.92555766e-01],
       [ 1.33977156e-01,  4.73240711e-02],
       [-1.46216050e-01,  5.04331818e-02],
       [-1.54402135e-01, -1.63191351e-02],
       [-1.38410747e-01, -2.22386562e-02],
       [ 3.73926495e-02,  4.58552864e-03],
       [ 2.83284103e-03, -1.01272611e-01],
       [-1.66051874e-01, -9.92670964e-02],
       [-8.84041921e-02,  1.27159443e-01],
       [-3.11746439e-02,  1.61853673e-01],
       [-6.55168818e-02, -3.75675403e-02],
       [-1.29270117e-01, -9.13063766e-02],
       [ 1.48211915e-01, -1.27791856e-01],
       [ 1.57954878e-01, -1.54188646e-01],
       [ 1.72134740e-01, -3.85992263e-02],
       [ 7.04035803e-02, -2.33758658e-02],
       [-3.02769794e-02,  3.29192873e-02],
       [-6.06368377e-02, -1.06100933e-01],
       [-1.58112176e-01, -3.57916746e-02],
       [ 7.88530375e-02, -1.89667594e-03],
       [ 2.75626861e-02,  2.76342760e-02],
       [ 1.44381517e-01,  3.57553881e-02],
       [ 3.10980355e-02,  1.28506565e-01],
       [ 5.84246616e-02,  2.17828882e-01],
       [ 4.75357745e-02, -1.35324623e-02],
       [-1.13048033e-01,  1.58326562e-01],
       [ 1.15842556e-01,  6.12113597e-02],
       [ 1.96025458e-02,  1.76750109e-01],
       [-1.00903295e-01, -1.09764736e-03],
       [ 1.38810318e-02, -4.00093360e-02],
       [ 6.42832923e-03, -3.63489578e-02],
       [ 3.69716195e-02,  1.22573707e-01],
       [ 2.75443004e-02,  1.25680733e-01],
       [-1.91245060e-01,  5.79685263e-02],
       [-1.79945557e-01, -9.28970429e-02],
       [-1.77788015e-01, -7.98608655e-02],
       [ 2.69624665e-03, -1.72569705e-01],
       [ 4.41127258e-03, -1.34701796e-01],
       [-3.05616731e-02,  3.29248847e-02],
       [ 3.85307071e-02,  1.50202253e-01],
       [ 3.81478564e-03,  5.50686539e-03],
       [-2.04784889e-02,  2.70031118e-02],
       [ 7.41809141e-03, -9.49372513e-02],
       [ 1.27580239e-02, -2.46457926e-02],
       [ 2.58126416e-01,  1.75361565e-01],
       [ 4.37388728e-02,  5.89424462e-02],
       [-1.24474764e-01, -2.95994783e-02],
       [-3.06768815e-02,  1.05785623e-01],
       [-8.82468245e-02, -1.25218325e-02],
       [-2.58852315e-01, -2.25275083e-02],
       [-2.35667599e-01, -6.42076969e-02],
       [-2.05519877e-01, -4.15301039e-02],
       [-2.78532778e-01, -1.67469576e-01],
       [ 7.36583223e-02, -2.12477046e-01],
       [-7.28493967e-02,  7.74528296e-02],
       [ 2.54082019e-01, -7.84302481e-02],
       [ 9.02161136e-02, -5.05956893e-03],
       [ 2.17977821e-01, -1.01215492e-01],
       [ 8.44611260e-02,  2.71260115e-02],
       [ 8.57071705e-02, -2.40526014e-02],
       [ 2.94712888e-02, -1.49515882e-01],
       [-9.08173001e-03, -1.01396690e-01],
       [ 1.86761240e-02, -1.06231067e-01],
       [ 5.64919142e-02,  4.81560484e-02],
       [ 4.37888899e-02,  5.92536650e-02],
       [ 2.72099797e-02,  2.96352718e-02],
       [-5.85508135e-02,  4.64670621e-02],
       [-3.90040666e-02,  2.32550362e-01],
       [ 1.37833457e-01,  1.54859836e-01],
       [-7.38899249e-03, -3.38112291e-02],
       [ 1.15419799e-01,  9.36930797e-03],
       [ 1.05724240e-01, -1.69773945e-01],
       [ 1.45605968e-01, -3.94449385e-02],
       [-3.82400844e-02, -6.68749500e-02],
       [ 7.25167824e-03, -2.81907952e-02],
       [-2.55912795e-02, -2.44442244e-02],
       [-3.79933776e-02,  3.03413901e-03],
       [ 1.28152509e-01, -2.55148775e-01],
       [ 4.03912278e-02, -1.09923145e-01],
       [ 4.97950129e-02, -9.21530307e-02],
       [-1.50774672e-01, -1.32769670e-02],
       [ 9.73476855e-02, -1.60024624e-01],
       [ 1.35056644e-01, -1.12864834e-01],
       [ 6.13958875e-02, -1.61722268e-01],
       [-2.74767350e-03,  4.91433254e-02],
       [ 5.68916875e-02,  1.97802823e-01],
       [ 1.46187033e-01,  1.42810080e-01],
       [ 2.47486969e-01,  1.15304356e-01],
       [ 2.06542302e-01,  2.79950825e-02],
       [ 1.09925733e-01, -5.57448411e-02],
       [ 1.53921260e-01, -1.45702783e-01],
       [ 1.55195664e-01, -9.19164972e-02],
       [ 1.94722541e-01,  2.91286503e-02],
       [ 2.79425886e-01,  8.76417943e-02],
       [-1.74910823e-02,  3.71255798e-02],
       [-1.25946260e-01, -3.32651943e-02],
       [ 8.81497131e-02,  4.71207839e-02],
       [-2.58181863e-02, -7.78113447e-02],
       [-9.63088386e-03, -1.60561687e-01],
       [-7.19294697e-02, -4.90798965e-02],
       [ 7.95664688e-02,  3.63361990e-02],
       [-1.89345716e-01,  4.86047724e-02],
       [-8.74695009e-02,  6.56914147e-02],
       [ 1.17886218e-01, -1.73478120e-01],
       [-1.67233665e-04, -2.76484279e-02],
       [-1.58243057e-01,  1.33770691e-01],
       [-4.22858671e-02,  1.51543744e-01],
       [-7.82372997e-02,  1.57148241e-01],
       [ 6.77285057e-02,  1.01861923e-01],
       [ 5.73043421e-02,  7.79652852e-02],
       [-5.76823554e-02,  2.42297746e-02],
       [-4.40934309e-02,  5.04542737e-02],
       [ 7.79357092e-02, -8.06264713e-02],
       [ 2.64669516e-02,  1.07832319e-01],
       [-6.11253471e-02, -2.83088422e-02],
       [-1.03320544e-02,  7.02840980e-02],
       [-4.02342163e-03,  1.68038108e-01],
       [ 8.36676874e-02,  1.68201061e-01],
       [ 9.72454939e-02,  3.16865840e-01],
       [ 2.81065780e-02, -4.19193090e-02],
       [ 1.74478725e-01, -6.67295976e-02],
       [ 9.80274070e-02,  9.75902697e-02],
       [-1.11212251e-01, -7.63695866e-02],
       [-2.15733919e-01, -1.17598422e-01],
       [-6.39032989e-02, -6.38042686e-03],
       [-4.32423152e-03, -1.44466802e-01],
       [-2.33172459e-01, -6.67980424e-02],
       [-1.63763833e-01,  1.25395560e-02],
       [-1.16865539e-02,  2.00939212e-02],
       [ 7.01700316e-02,  3.29680980e-02]]), endog_names=['gdp', 'inflation'], exog=None, exog_names=None, index=DatetimeIndex(['2000-01-01', '2000-04-01', '2000-07-01', '2000-10-01',
               '2001-01-01', '2001-04-01', '2001-07-01', '2001-10-01',
               '2002-01-01', '2002-04-01',
               ...
               '2047-07-01', '2047-10-01', '2048-01-01', '2048-04-01',
               '2048-07-01', '2048-10-01', '2049-01-01', '2049-04-01',
               '2049-07-01', '2049-10-01'],
              dtype='datetime64[us]', length=200, freq='QS-JAN'))

## Select lag order

Use information criteria to find the optimal lag length.

In [3]:
ic = select_lag_order(data, max_lags=8)
print(f"AIC: {ic.aic}, BIC: {ic.bic}, HQ: {ic.hq}")
ic.summary()

AIC: 1, BIC: 1, HQ: 1

          aic       bic        hq
lag
1   -9.368291 -9.268995 -9.328103
2   -9.350139 -9.184065 -9.282918
3   -9.334984 -9.101660 -9.240533
4   -9.332458 -9.031407 -9.210578
5   -9.319690 -8.950429 -9.170180
6   -9.288078 -8.850118 -9.110736
7   -9.247516 -8.740362 -9.042135
8   -9.259885 -8.683037 -9.026257

## Specify and estimate the model

Create a VAR specification and fit it. We use a small number of draws here for speed.

In [4]:
spec = VAR(lags="bic", prior="minnesota")
sampler = NUTSSampler(draws=500, tune=500, chains=2, cores=1, random_seed=42)
fitted = spec.fit(data, sampler=sampler)
fitted

Initializing NUTS using jitter+adapt_diag...
Sequential sampling (2 chains in 1 job)
NUTS: [intercept, B, sigma_sd, tril_offdiag]

/Users/thomaspinder/Developer/litterman/.venv/lib/python3.11/site-packages/rich/live.py:260: UserWarning: install
"ipywidgets" for Jupyter support
  warnings.warn('install "ipywidgets" for Jupyter support')

Sampling 2 chains for 500 tune and 500 draw iterations (1_000 + 1_000 draws total) took 2 seconds.
We recommend running at least 4 chains for robust computation of convergence diagnostics

FittedVAR(n_lags=1, n_vars=2, n_draws=500, n_chains=2)

## Inspect the posterior

Access the ArviZ InferenceData directly for diagnostics.

In [5]:
import arviz as az

az.summary(fitted.idata, var_names=["B", "intercept"])

,mean,sd,hdi_3%,hdi_97%,mcse_mean,mcse_sd,ess_bulk,ess_tail,r_hat
"B[0, 0]",0.606,0.059,0.504,0.722,0.002,0.002,963.0,711.0,1.0
"B[0, 1]",0.006,0.042,-0.067,0.084,0.001,0.001,1309.0,771.0,1.0
"B[1, 0]",0.003,0.040,-0.071,0.077,0.001,0.001,1457.0,754.0,1.0
"B[1, 1]",0.602,0.057,0.498,0.710,0.002,0.002,892.0,802.0,1.0
intercept[0],0.002,0.007,-0.011,0.016,0.000,0.000,1390.0,684.0,1.0
intercept[1],-0.002,0.006,-0.014,0.010,0.000,0.000,1115.0,788.0,1.0